services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./templates:/templates
      - ./config.py:/config.py
    working_dir: /
    command: sh -c "uvicorn app.main:main_app --host 0.0.0.0 --port 8000 --reload --reload-dir app"
    ports:
      - "8000:8000"
    networks:
      - network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - network

volumes:
  mongo-data: {}

networks:
  network:
    driver: bridge
